name: Story
version: @version@
main: io.github.paul1365972.story.Story
api-version: 1.15
authors: [Paul1365972]
description: Basic Paper plugin for managing custom data and attaching it to all minecraft objects
