name: Story
version: @version@
main: io.github.paul1365972.story.Story
api-version: 1.15
authors: [Paul1365972]
description: Basic Spigot plugin for attaching custom data to Blocks, Chunks, Worlds, Tile Entities, Items, Players and Entities
